// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// binFit64ToDepth
NumericMatrix binFit64ToDepth(NumericMatrix dmat, std::string bitdepth);
RcppExport SEXP feature2_binFit64ToDepth(SEXP dmatSEXP, SEXP bitdepthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< std::string >::type bitdepth(bitdepthSEXP);
    rcpp_result_gen = Rcpp::wrap(binFit64ToDepth(dmat, bitdepth));
    return rcpp_result_gen;
END_RCPP
}
// Blur2D
NumericMatrix Blur2D(NumericMatrix dmat, std::string bitdepth, int num_rows_kernel, int num_cols_kernel, int center_row, int center_col, std::string borderType);
RcppExport SEXP feature2_Blur2D(SEXP dmatSEXP, SEXP bitdepthSEXP, SEXP num_rows_kernelSEXP, SEXP num_cols_kernelSEXP, SEXP center_rowSEXP, SEXP center_colSEXP, SEXP borderTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< std::string >::type bitdepth(bitdepthSEXP);
    Rcpp::traits::input_parameter< int >::type num_rows_kernel(num_rows_kernelSEXP);
    Rcpp::traits::input_parameter< int >::type num_cols_kernel(num_cols_kernelSEXP);
    Rcpp::traits::input_parameter< int >::type center_row(center_rowSEXP);
    Rcpp::traits::input_parameter< int >::type center_col(center_colSEXP);
    Rcpp::traits::input_parameter< std::string >::type borderType(borderTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(Blur2D(dmat, bitdepth, num_rows_kernel, num_cols_kernel, center_row, center_col, borderType));
    return rcpp_result_gen;
END_RCPP
}
// borderTypeCode
int borderTypeCode(std::string borderType);
RcppExport SEXP feature2_borderTypeCode(SEXP borderTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type borderType(borderTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(borderTypeCode(borderType));
    return rcpp_result_gen;
END_RCPP
}
// CCF_2D_mod
List CCF_2D_mod(NumericMatrix dmat, NumericMatrix tmplte, int x_maxlag, int y_maxlag, std::string bitdepth);
RcppExport SEXP feature2_CCF_2D_mod(SEXP dmatSEXP, SEXP tmplteSEXP, SEXP x_maxlagSEXP, SEXP y_maxlagSEXP, SEXP bitdepthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tmplte(tmplteSEXP);
    Rcpp::traits::input_parameter< int >::type x_maxlag(x_maxlagSEXP);
    Rcpp::traits::input_parameter< int >::type y_maxlag(y_maxlagSEXP);
    Rcpp::traits::input_parameter< std::string >::type bitdepth(bitdepthSEXP);
    rcpp_result_gen = Rcpp::wrap(CCF_2D_mod(dmat, tmplte, x_maxlag, y_maxlag, bitdepth));
    return rcpp_result_gen;
END_RCPP
}
// CCF_2D
NumericMatrix CCF_2D(NumericMatrix dmat, NumericMatrix tmplte, int x_maxlag, int y_maxlag, std::string bitdepth);
RcppExport SEXP feature2_CCF_2D(SEXP dmatSEXP, SEXP tmplteSEXP, SEXP x_maxlagSEXP, SEXP y_maxlagSEXP, SEXP bitdepthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tmplte(tmplteSEXP);
    Rcpp::traits::input_parameter< int >::type x_maxlag(x_maxlagSEXP);
    Rcpp::traits::input_parameter< int >::type y_maxlag(y_maxlagSEXP);
    Rcpp::traits::input_parameter< std::string >::type bitdepth(bitdepthSEXP);
    rcpp_result_gen = Rcpp::wrap(CCF_2D(dmat, tmplte, x_maxlag, y_maxlag, bitdepth));
    return rcpp_result_gen;
END_RCPP
}
// Center2D
NumericMatrix Center2D(NumericMatrix dmat);
RcppExport SEXP feature2_Center2D(SEXP dmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    rcpp_result_gen = Rcpp::wrap(Center2D(dmat));
    return rcpp_result_gen;
END_RCPP
}
// testscale
void testscale(NumericMatrix dmat, std::string bitdepth, bool printQ);
RcppExport SEXP feature2_testscale(SEXP dmatSEXP, SEXP bitdepthSEXP, SEXP printQSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< std::string >::type bitdepth(bitdepthSEXP);
    Rcpp::traits::input_parameter< bool >::type printQ(printQSEXP);
    testscale(dmat, bitdepth, printQ);
    return R_NilValue;
END_RCPP
}
// testConvert
NumericMatrix testConvert(NumericMatrix dmat, bool printQ);
RcppExport SEXP feature2_testConvert(SEXP dmatSEXP, SEXP printQSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< bool >::type printQ(printQSEXP);
    rcpp_result_gen = Rcpp::wrap(testConvert(dmat, printQ));
    return rcpp_result_gen;
END_RCPP
}
// Circular_Mask_ROI
NumericMatrix Circular_Mask_ROI(NumericMatrix dmat, int xc_idx, int yc_idx, int pix_radius);
RcppExport SEXP feature2_Circular_Mask_ROI(SEXP dmatSEXP, SEXP xc_idxSEXP, SEXP yc_idxSEXP, SEXP pix_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< int >::type xc_idx(xc_idxSEXP);
    Rcpp::traits::input_parameter< int >::type yc_idx(yc_idxSEXP);
    Rcpp::traits::input_parameter< int >::type pix_radius(pix_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(Circular_Mask_ROI(dmat, xc_idx, yc_idx, pix_radius));
    return rcpp_result_gen;
END_RCPP
}
// Crop_Retangular_ROI
NumericMatrix Crop_Retangular_ROI(NumericMatrix dmat, unsigned int Xstart_index, unsigned int Ystart_index, unsigned int Width, unsigned int Height);
RcppExport SEXP feature2_Crop_Retangular_ROI(SEXP dmatSEXP, SEXP Xstart_indexSEXP, SEXP Ystart_indexSEXP, SEXP WidthSEXP, SEXP HeightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Xstart_index(Xstart_indexSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Ystart_index(Ystart_indexSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Width(WidthSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Height(HeightSEXP);
    rcpp_result_gen = Rcpp::wrap(Crop_Retangular_ROI(dmat, Xstart_index, Ystart_index, Width, Height));
    return rcpp_result_gen;
END_RCPP
}
// DFTMag2D
NumericMatrix DFTMag2D(NumericMatrix dmat, std::string bitdepth);
RcppExport SEXP feature2_DFTMag2D(SEXP dmatSEXP, SEXP bitdepthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< std::string >::type bitdepth(bitdepthSEXP);
    rcpp_result_gen = Rcpp::wrap(DFTMag2D(dmat, bitdepth));
    return rcpp_result_gen;
END_RCPP
}
// Display2D_openCV
void Display2D_openCV(NumericMatrix dmat, int rowWidth, int colWidth, std::string bitdepth, std::string file_ext, bool printQ, std::string exe_path);
RcppExport SEXP feature2_Display2D_openCV(SEXP dmatSEXP, SEXP rowWidthSEXP, SEXP colWidthSEXP, SEXP bitdepthSEXP, SEXP file_extSEXP, SEXP printQSEXP, SEXP exe_pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< int >::type rowWidth(rowWidthSEXP);
    Rcpp::traits::input_parameter< int >::type colWidth(colWidthSEXP);
    Rcpp::traits::input_parameter< std::string >::type bitdepth(bitdepthSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_ext(file_extSEXP);
    Rcpp::traits::input_parameter< bool >::type printQ(printQSEXP);
    Rcpp::traits::input_parameter< std::string >::type exe_path(exe_pathSEXP);
    Display2D_openCV(dmat, rowWidth, colWidth, bitdepth, file_ext, printQ, exe_path);
    return R_NilValue;
END_RCPP
}
// Fill_Holes
NumericMatrix Fill_Holes(NumericMatrix dmat, NumericMatrix mask);
RcppExport SEXP feature2_Fill_Holes(SEXP dmatSEXP, SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(Fill_Holes(dmat, mask));
    return rcpp_result_gen;
END_RCPP
}
// Filter2D
NumericMatrix Filter2D(NumericMatrix dmat, NumericMatrix kernel, std::string bitdepth);
RcppExport SEXP feature2_Filter2D(SEXP dmatSEXP, SEXP kernelSEXP, SEXP bitdepthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< std::string >::type bitdepth(bitdepthSEXP);
    rcpp_result_gen = Rcpp::wrap(Filter2D(dmat, kernel, bitdepth));
    return rcpp_result_gen;
END_RCPP
}
// FindHoles
NumericMatrix FindHoles(NumericMatrix dmat_mask, std::string mode, std::string approx_method, double big_hole_tol);
RcppExport SEXP feature2_FindHoles(SEXP dmat_maskSEXP, SEXP modeSEXP, SEXP approx_methodSEXP, SEXP big_hole_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat_mask(dmat_maskSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< std::string >::type approx_method(approx_methodSEXP);
    Rcpp::traits::input_parameter< double >::type big_hole_tol(big_hole_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(FindHoles(dmat_mask, mode, approx_method, big_hole_tol));
    return rcpp_result_gen;
END_RCPP
}
// check_rx
void check_rx();
RcppExport SEXP feature2_check_rx() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    check_rx();
    return R_NilValue;
END_RCPP
}
// error
void error();
RcppExport SEXP feature2_error() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    error();
    return R_NilValue;
END_RCPP
}
// GaussianBlur2D
NumericMatrix GaussianBlur2D(NumericMatrix dmat, std::string bitdepth, int num_rows_kernel, int num_cols_kernel, double sigmaX, double sigmaY, std::string borderType);
RcppExport SEXP feature2_GaussianBlur2D(SEXP dmatSEXP, SEXP bitdepthSEXP, SEXP num_rows_kernelSEXP, SEXP num_cols_kernelSEXP, SEXP sigmaXSEXP, SEXP sigmaYSEXP, SEXP borderTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< std::string >::type bitdepth(bitdepthSEXP);
    Rcpp::traits::input_parameter< int >::type num_rows_kernel(num_rows_kernelSEXP);
    Rcpp::traits::input_parameter< int >::type num_cols_kernel(num_cols_kernelSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaX(sigmaXSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaY(sigmaYSEXP);
    Rcpp::traits::input_parameter< std::string >::type borderType(borderTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(GaussianBlur2D(dmat, bitdepth, num_rows_kernel, num_cols_kernel, sigmaX, sigmaY, borderType));
    return rcpp_result_gen;
END_RCPP
}
// lewis
NumericMatrix lewis(int num_svals, IntegerVector nz_idxs, NumericVector ff, int offset1, int offset2, int offset3);
RcppExport SEXP feature2_lewis(SEXP num_svalsSEXP, SEXP nz_idxsSEXP, SEXP ffSEXP, SEXP offset1SEXP, SEXP offset2SEXP, SEXP offset3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_svals(num_svalsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nz_idxs(nz_idxsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ff(ffSEXP);
    Rcpp::traits::input_parameter< int >::type offset1(offset1SEXP);
    Rcpp::traits::input_parameter< int >::type offset2(offset2SEXP);
    Rcpp::traits::input_parameter< int >::type offset3(offset3SEXP);
    rcpp_result_gen = Rcpp::wrap(lewis(num_svals, nz_idxs, ff, offset1, offset2, offset3));
    return rcpp_result_gen;
END_RCPP
}
// numerator_trick
void numerator_trick(NumericMatrix A, NumericMatrix B);
RcppExport SEXP feature2_numerator_trick(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    numerator_trick(A, B);
    return R_NilValue;
END_RCPP
}
// Pad_NumericMatrix
NumericMatrix Pad_NumericMatrix(NumericMatrix dmat, int top, int bottom, int left, int right, std::string border_type, double value);
RcppExport SEXP feature2_Pad_NumericMatrix(SEXP dmatSEXP, SEXP topSEXP, SEXP bottomSEXP, SEXP leftSEXP, SEXP rightSEXP, SEXP border_typeSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< int >::type top(topSEXP);
    Rcpp::traits::input_parameter< int >::type bottom(bottomSEXP);
    Rcpp::traits::input_parameter< int >::type left(leftSEXP);
    Rcpp::traits::input_parameter< int >::type right(rightSEXP);
    Rcpp::traits::input_parameter< std::string >::type border_type(border_typeSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(Pad_NumericMatrix(dmat, top, bottom, left, right, border_type, value));
    return rcpp_result_gen;
END_RCPP
}
// numvec_to_python
void numvec_to_python(std::string name, NumericVector x);
RcppExport SEXP feature2_numvec_to_python(SEXP nameSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    numvec_to_python(name, x);
    return R_NilValue;
END_RCPP
}
// pyrun
void pyrun(std::string command);
RcppExport SEXP feature2_pyrun(SEXP commandSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type command(commandSEXP);
    pyrun(command);
    return R_NilValue;
END_RCPP
}
// initialize_python
void initialize_python();
RcppExport SEXP feature2_initialize_python() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    initialize_python();
    return R_NilValue;
END_RCPP
}
// finalize_python
void finalize_python();
RcppExport SEXP feature2_finalize_python() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    finalize_python();
    return R_NilValue;
END_RCPP
}
// Resize
NumericMatrix Resize(NumericMatrix dmat, unsigned int num_rows, unsigned int num_cols);
RcppExport SEXP feature2_Resize(SEXP dmatSEXP, SEXP num_rowsSEXP, SEXP num_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_rows(num_rowsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_cols(num_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(Resize(dmat, num_rows, num_cols));
    return rcpp_result_gen;
END_RCPP
}
// Reverse_Mat
arma::mat Reverse_Mat(NumericMatrix dmat);
RcppExport SEXP feature2_Reverse_Mat(SEXP dmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    rcpp_result_gen = Rcpp::wrap(Reverse_Mat(dmat));
    return rcpp_result_gen;
END_RCPP
}
// RollColumns
NumericMatrix RollColumns(NumericMatrix dmat, std::string direction, unsigned int n);
RcppExport SEXP feature2_RollColumns(SEXP dmatSEXP, SEXP directionSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< std::string >::type direction(directionSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(RollColumns(dmat, direction, n));
    return rcpp_result_gen;
END_RCPP
}
// RollRows
NumericMatrix RollRows(NumericMatrix dmat, std::string direction, unsigned int n);
RcppExport SEXP feature2_RollRows(SEXP dmatSEXP, SEXP directionSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< std::string >::type direction(directionSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(RollRows(dmat, direction, n));
    return rcpp_result_gen;
END_RCPP
}
// Sobel
NumericMatrix Sobel(NumericMatrix dmat, std::string bitdepth, int ddepth, int dx, int dy, int ksize, double scale, double delta, int borderType);
RcppExport SEXP feature2_Sobel(SEXP dmatSEXP, SEXP bitdepthSEXP, SEXP ddepthSEXP, SEXP dxSEXP, SEXP dySEXP, SEXP ksizeSEXP, SEXP scaleSEXP, SEXP deltaSEXP, SEXP borderTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< std::string >::type bitdepth(bitdepthSEXP);
    Rcpp::traits::input_parameter< int >::type ddepth(ddepthSEXP);
    Rcpp::traits::input_parameter< int >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< int >::type dy(dySEXP);
    Rcpp::traits::input_parameter< int >::type ksize(ksizeSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type borderType(borderTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(Sobel(dmat, bitdepth, ddepth, dx, dy, ksize, scale, delta, borderType));
    return rcpp_result_gen;
END_RCPP
}
// TemplateMatch
NumericMatrix TemplateMatch(NumericMatrix dmat_fixed, NumericMatrix template_mov, std::string bitdepth);
RcppExport SEXP feature2_TemplateMatch(SEXP dmat_fixedSEXP, SEXP template_movSEXP, SEXP bitdepthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat_fixed(dmat_fixedSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type template_mov(template_movSEXP);
    Rcpp::traits::input_parameter< std::string >::type bitdepth(bitdepthSEXP);
    rcpp_result_gen = Rcpp::wrap(TemplateMatch(dmat_fixed, template_mov, bitdepth));
    return rcpp_result_gen;
END_RCPP
}
// vec2mat
NumericMatrix vec2mat(NumericVector row_idxs, NumericVector col_idxs, NumericVector mat_elems, int num_rows, int num_cols);
RcppExport SEXP feature2_vec2mat(SEXP row_idxsSEXP, SEXP col_idxsSEXP, SEXP mat_elemsSEXP, SEXP num_rowsSEXP, SEXP num_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type row_idxs(row_idxsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type col_idxs(col_idxsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mat_elems(mat_elemsSEXP);
    Rcpp::traits::input_parameter< int >::type num_rows(num_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type num_cols(num_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(vec2mat(row_idxs, col_idxs, mat_elems, num_rows, num_cols));
    return rcpp_result_gen;
END_RCPP
}
// vltest
void vltest();
RcppExport SEXP feature2_vltest() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    vltest();
    return R_NilValue;
END_RCPP
}
// WriteMat
void WriteMat(NumericMatrix dmat, std::string bitdepth, std::string fpath);
RcppExport SEXP feature2_WriteMat(SEXP dmatSEXP, SEXP bitdepthSEXP, SEXP fpathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< std::string >::type bitdepth(bitdepthSEXP);
    Rcpp::traits::input_parameter< std::string >::type fpath(fpathSEXP);
    WriteMat(dmat, bitdepth, fpath);
    return R_NilValue;
END_RCPP
}
