# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testscale <- function(dmat, bitdepth, printQ = FALSE) {
    invisible(.Call('feature2_testscale', PACKAGE = 'feature2', dmat, bitdepth, printQ))
}

testConvert <- function(dmat, printQ = FALSE) {
    .Call('feature2_testConvert', PACKAGE = 'feature2', dmat, printQ)
}

DFTMag2D <- function(dmat, bitdepth) {
    .Call('feature2_DFTMag2D', PACKAGE = 'feature2', dmat, bitdepth)
}

Display2D_openCV <- function(dmat, rowWidth, colWidth, bitdepth, file_ext, printQ, exe_path) {
    invisible(.Call('feature2_Display2D_openCV', PACKAGE = 'feature2', dmat, rowWidth, colWidth, bitdepth, file_ext, printQ, exe_path))
}

Filter2D <- function(dmat, kernel, bitdepth) {
    .Call('feature2_Filter2D', PACKAGE = 'feature2', dmat, kernel, bitdepth)
}

numvec_to_python <- function(name, x) {
    invisible(.Call('feature2_numvec_to_python', PACKAGE = 'feature2', name, x))
}

pyrun <- function(command) {
    invisible(.Call('feature2_pyrun', PACKAGE = 'feature2', command))
}

initialize_python <- function() {
    invisible(.Call('feature2_initialize_python', PACKAGE = 'feature2'))
}

finalize_python <- function() {
    invisible(.Call('feature2_finalize_python', PACKAGE = 'feature2'))
}

Resize <- function(dmat, num_rows, num_cols) {
    .Call('feature2_Resize', PACKAGE = 'feature2', dmat, num_rows, num_cols)
}

Sobel <- function(dmat, bitdepth, ddepth, dx, dy, ksize = 3L, scale = 1.0, delta = 0.0, borderType = 4L) {
    .Call('feature2_Sobel', PACKAGE = 'feature2', dmat, bitdepth, ddepth, dx, dy, ksize, scale, delta, borderType)
}

WriteMat <- function(dmat, bitdepth, fpath) {
    invisible(.Call('feature2_WriteMat', PACKAGE = 'feature2', dmat, bitdepth, fpath))
}

